export { default as logo } from "../assets/logo.png"
export { default as cpp } from "../assets/tech/cpp.png";
export { default as css } from "../assets/tech/css.png";
export { default as firebase } from "../assets/tech/firebase.png";
export { default as flask } from "../assets/tech/flask.svg";
export { default as git } from "../assets/tech/git.png";
export { default as github } from "../assets/tech/github.svg";
export { default as html } from "../assets/tech/html.png";
export { default as javascript } from "../assets/tech/javascript.png";
export { default as nextjs } from "../assets/tech/nextjs.png";
export { default as python } from "../assets/tech/python.png";
export { default as reactjs } from "../assets/tech/react.png";
export { default as tailwind } from "../assets/tech/tailwind.png";
export { default as vercel } from "../assets/tech/vercel.png";
export { default as portfolio } from "../assets/projects/portfolio.png"
export { default as vibeshare } from "../assets/projects/vibeshare.png"
export { default as anonymouschat } from "../assets/projects/anonymouschat.png"
export { default as googledocs } from "../assets/projects/googledocs.png"
export { default as senior } from "../assets/senior.png"
export { default as external } from "../assets/external.svg"
export { default as code } from "../assets/code.svg"
export { default as gmail } from "../assets/gmail.svg"
export { default as instagram } from "../assets/instagram.svg"
export { default as linkedin } from "../assets/linkedin.svg"
export { default as discord } from "../assets/discord.svg"
export { default as about } from "../assets/about.png"
export { default as contact } from "../assets/contact.png"
export { default as more } from "../assets/more.svg"
export { default as user } from "../assets/user.png"
export { default as projects } from "../assets/projects.png"
export { default as tech } from "../assets/tech.png"
export { default as contact_icon } from "../assets/contact-sidebar.png"
export { default as experiences } from "../assets/experiences.png"